### ISSUE TITLE
The module attributes mean that you can't configure the probes at runtime

### ISSUE THREAD

**Issue by knewter** [KamilLelonek/healthchex#2]
I would prefer `Application.get_env` at runtime. Right now the probe configuration is forced at compile time as far as I can tell.

**Comment by KamilLelonek** [comment]
Hello, I agree we can do that. Can you prepare a PR for it?

**Comment by KamilLelonek** [comment]
Done in https://github.com/KamilLelonek/healthchex/commit/78d5311090172ee35228f412822113a0240ca88f
